name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build and Test
      run: ./gradlew build test
