name: Testing  # Nombre del flujo de trabajo

on:
  push:  # Desencadenado en cada push
    branches:
      - master  # A la rama master

jobs:
  test:
    name: Run tests  # Nombre del trabajo
    runs-on: ubuntu-latest  # Se ejecuta en una máquina virtual con Ubuntu

    steps:  # Pasos que se ejecutarán en este trabajo
      - name: Checkout code  # Paso para clonar el repositorio
        uses: actions/checkout@v2  # Utiliza la acción de checkout

      - name: Set up JDK 17  # Paso para configurar JDK 17
        uses: actions/setup-java@v2  # Utiliza la acción para configurar Java
        with:
          java-version: 17  # Versión de Java a configurar

      - name: Grant execute permission for Gradle wrapper  # Paso para otorgar permisos de ejecución al wrapper de Gradle
        run: chmod +x ./gradlew  # Comando para otorgar permisos de ejecución al wrapper de Gradle

      - name: Run tests with Gradle  # Paso para ejecutar pruebas con Gradle
        run: ./gradlew test  # Comando para ejecutar pruebas con Gradle
