name: Android Build and Basic Test

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: 'my-repo'  # Opcional: puedes especificar la ruta donde se va a clonar el repositorio
        ref: ${{ github.ref }}  # Clonar la rama actual
        fetch-depth: 0  # Clonar todo el historial del repositorio

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Make Gradlew executable
      run: chmod +x my-repo/gradlew

    - name: Build and test
      run: |
        cd my-repo
        ./gradlew build test
